project:
  - title: "Samsung Display: Bistable Kirigami Integration for Curved Display Corner"
    image: samsung_display.png
    detail: >
      <p>Integrated a bistable kirigami pattern into curved-display corner regions to enable controlled shape transition and robustness under constrained geometry.</p>
      <p>Iterated pattern parameterization and stability-focused analysis to satisfy corner curvature and boundary constraints; prioritized manufacturability and repeatable behavior.</p>
    tags:
      - Kirigami
      - Display
      - Mechanics
    description: >-
      Integrated a bistable kirigami pattern into curved-display corner regions.
    id: samsung_display

  - title: "LG Electronics: Kirigami-Enhanced Pulp-Mold Packaging for Impact Absorption"
    image: lg_electronics.png
    detail: >
      <p>Applied kirigami patterns to pulp-mold packaging to increase deformation stroke and improve energy absorption without adding bulk material.</p>
      <p>Developed practical pattern guidelines considering pulp-mold forming constraints; summarized expected mechanical behavior and prototyping directions.</p>
    tags:
      - Kirigami
      - Packaging
      - Impact Absorption
    description: >-
      Applied kirigami patterns to pulp-mold packaging to increase deformation stroke.
    id: lg_electronics

  - title: "AI Factory Hackathon"
    image: ai_factory.gif
    detail: >
      <p>Participated in the AI Factory Hackathon to develop innovative AI models designed to solve practical and real-world problems.</p>
      <p>Focused on efficient data preprocessing, model tuning, and algorithm configuration to provide optimal solutions under the given competition scenarios.</p>
    tags:
      - AI
      - Hackathon
      - Data Analysis
    description: >-
      AI model development and implementation at AI Factory Hackathon.
    id: ai_factory

  - title: "Semiconductor Solverton Competition Top Prize"
    image: solverton.jpg
    detail: >
      <p>Optimized AC performance of GAA NS FET by analyzing and optimizing resistance, capacitance, and frequency gain compared to FinFET through structural modeling and process-driven device design.</p>
      <p>Proposed a new design with enhanced performance via TCAD simulation. Recognized with the Deputy Prime Minister and Education Minister Prize.</p>
    tags:
      - Semiconductor
      - TCAD
      - Simulation
    description: >-
      Optimized AC performance of GAA NS FET in the Semiconductor Solverton.
    id: solverton